# Generated by Django 4.1.3 on 2023-01-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, verbose_name='カテゴリー')),
                ('ja_word', models.CharField(max_length=200, verbose_name='日本語')),
                ('en_word', models.CharField(max_length=200, verbose_name='英語')),
                ('memo', models.CharField(max_length=200, verbose_name='メモ')),
            ],
        ),
    ]
