# Generated by Django 4.1.3 on 2023-01-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlists',
            name='category',
            field=models.CharField(max_length=50, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='wordlists',
            name='en_word',
            field=models.TextField(verbose_name='英語'),
        ),
        migrations.AlterField(
            model_name='wordlists',
            name='ja_word',
            field=models.CharField(max_length=300, verbose_name='日本語'),
        ),
        migrations.AlterField(
            model_name='wordlists',
            name='memo',
            field=models.TextField(verbose_name='メモ'),
        ),
        migrations.AlterModelTable(
            name='wordlists',
            table='wordlists',
        ),
    ]
