# Generated by Django 4.1.3 on 2023-02-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_list', '0002_alter_wordlists_category_alter_wordlists_en_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlists',
            name='file',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='wordlists',
            name='file_name',
            field=models.CharField(default=2, max_length=100, verbose_name='ダウンロード時に使うファイル名'),
            preserve_default=False,
        ),
    ]
