# Generated by Django 4.1.3 on 2023-02-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_list', '0003_wordlists_file_wordlists_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordlists',
            name='file_name',
        ),
    ]
